{% set name = "django-registration" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_registration-{{ version }}.tar.gz
  sha256: 06864f9da0bc4d7b073fb2da98d95d12428357ab0bc46e33f79c26707ec06bbe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2,!=5.0.*
    - confusable-homoglyphs >=3.0

test:
  imports:
    - django_registration
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: An extensible user-registration application for Django.
  license: BSD-3-Clause
  home: https://github.com/ubernostrum/django-registration
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
