{% set name = "django-registration" %}
{% set version = "3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-registration-{{ version }}.tar.gz
  sha256: 1a0ccef7ef71e67a78a551abd8ad378977dc14a036f1fcd8be422a68bd5254a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - django >=3.2,!=4.0.*
    - confusable-homoglyphs >=3.0,<4.dev0

test:
  imports:
    - django_registration
  commands:
    - pip check
  requires:
    - pip

about:
  summary: An extensible user-registration application for Django.
  license: BSD-3-Clause
  home: https://github.com/ubernostrum/django-registration
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
