{% set name = "django-registration" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e64b0b1d24886fc740122862630ec00b8c2ffd4ab6d0e0a9bced870374d1436b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - django >=3.2,!=4.0.*
    - confusable-homoglyphs >=3.0,<4.dev0

test:
  imports:
    - django_registration
  commands:
    - pip check
  requires:
    - pip

about:
  summary: An extensible user-registration application for Django.
  license: BSD-3-Clause
  home: https://github.com/ubernostrum/django-registration
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
