schema_version: 1

context:
  name: django-registration
  version: 5.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_registration-${{ version }}.tar.gz
  sha256: 06864f9da0bc4d7b073fb2da98d95d12428357ab0bc46e33f79c26707ec06bbe

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2,!=5.0.*
    - confusable-homoglyphs >=3.0

tests:
  - python:
      imports:
        - django_registration
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: An extensible user-registration application for Django.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/ubernostrum/django-registration

extra:
  recipe-maintainers:
    - rxm7706
